---
title: "Executive Summary"
author: "Xiaolin Zheng, Sheng Cao, Xiangting Ye, Tianjiao Gao"
date: "5/13/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Covid Response Policy among Countries with Different Happiness Levels

## 1. Analysis Question and Policy Application：
Our research is a cluster analysis focusing on covid response policy among countries with different happiness levels. We'd like to explore between-group differences and within-group commonalities in covid response policy across countries with different levels of happiness.  Our findings imply that some kinds of COVID response policies are associated with happiness of the public, and could be taken into consideration when a COVID response policy is made.

## 2. Data Sources:
For this analysis, we combine two data sources. The first one is The World Happiness Report 2019 and 2020. Happiness score can be explained by the other six factors, namely  GDP per capita, Healthy Life Expectancy, Social support, Freedom to make life choices, Generosity, and Corruption Perception, which are also included in the dataset.

The second source is the database of variation in government responses to COVID-19 from 2020 to now collected by the Oxford COVID-19 Government Response Tracker (OXCGRT). It offered the composition and calculation of several policy indices, among which we took advantage of 4 indices, namely government response index, containment and health index, stringency index and economic support index.

## 3.Methods Used: 
We use predicting model, cluster analysis, geospatial analysis, as well as heatmap. This is because we want to get the 2021’s happiness score which we don’t have and see the difference of happiness level between various countries and also make comparisons between different groups of countries.

## 4.Project Key Findings:
To begin with, economic support index, containment and health index have larger differences between groups based on happiness index compared with stringency index and government response index. This phenomenon may be explained by the relationship between countries’ economic conditions and citizens’ state of happiness. Developed countries usually enjoy higher happiness index with the ability to provide greater economic support and health investment.

In addition, stringency index’s difference between groups is relatively indistinctive. This finding might be because COVID closure policy would not heavily affect people’s happiness.  And such policy would significantly influence people’s happiness, but its effects can be partly offset by economic support and health investment provided by governments. Considering the evidence in the fields of sociology and psychology, the latter may be more reasonable.

Last, the government response index’s difference between groups is relatively insignificant. Regarding this index is the aggregation of other 3 indexes, the between-group variation of economic support index,containment and health index may be partly offset by stringency index. 

## 5.Challenges and Extra Work We Would Like to Do：
First of all, the four indices in the COVID-19 dataset are the simple averages of all the individual component indicators. However, some indicators we think are more important than other indicators. So, if there could be additional time, we would like to reweigh those different components and calculate the indicators based on our own comprehension.

Secondly, it is a pity for us to collect those variables in the year of 2021, which could have been applied to predict happiness index. If there could be more time, we would be more willing to predict happiness in 2021 for each country.

If time allowed, we would like to do a more detailed analysis by a specific region like a continent or some specific countries, and probably analyze whether there are changed pattern for happiness levels between 2019 and 2020.
